### ISSUE TITLE
Rename "navto" to "cd"

### ISSUE THREAD

**Issue by dabenzel** [SNException/SN-Console#3]
https://github.com/SNException/SN-Console/blob/92f6f4b5128d8b21e93417f9e2e58be86d04c1b8/src/main/java/nschultz/console/commands/types/NavigateToCommand.java#L78

I suggest to rename the "navto" command to "cd" (change directory) because windows and linux are using it in their cli for the same purpose

**Comment by SNException** [comment]
Yes, I agree. Very nice suggestion, thank you 👍 
This means we do not need the **NavigateCommand** class anymore because the user should be able to just type **cd** to output the current working directory.

Would you like to take care of this issue? I'm going to assign it to you if that's the case.

I put a defintion of done together:
- change command exectution name from **navto** to **cd**
- rename class from **NavigateToCommand** to **ChangeDirectoryCommand**
- delete the **NavigateCommand** class since we do not need it anymore. We can use the
**ChangeDirectoryCommand** to display the current working directory by just typing **cd**. This requires to check if no arguments have been provided and if so output the working directory
- rename the navto.html file to cd.html and also adjust it's html code so it fits the new name and argument count of the **ChangeDirectoryCommand**
- delete **nav.html** file since we do not have the **NavigateCommand** class anymore

Thanks again! 😃

**Comment by dabenzel** [comment]
I'll have a look at it the next days!
